"""The factor registry: 500+ deterministic factors, generated by systematic
parameterization rather than written by hand.

`quant/features.py` holds ~50 hand-picked features computed for the *latest* bar.
This module is the industrial version of the same idea: every factor is one entry
in `FACTOR_REGISTRY`, computable at *every* bar, and immediately rankable by the
Phase-7 IC machinery in `quant/ranking.py`.

Why a registry instead of a big function
----------------------------------------
Adding a factor must be one dict entry and nothing else. The moment a factor
lands in `FACTOR_REGISTRY` it appears in `factors <ASSET>` output, gets scored by
IC, and gets covered by the lookahead test — with no other change anywhere. A
god-function cannot give that guarantee.

The lookahead rule, enforced structurally
-----------------------------------------
A factor is a pure function `fn(bars, t) -> float | None` that may read only
indices `[0..t]`. Nothing in this file may index past `t`. `tests/test_factors.py`
pins this for *every* registry entry by recomputing each factor on a series
truncated at `t` and asserting the value is identical. If you add a factor that
peeks at the future, that test fails.

Coverage honesty
----------------
Every factor declares `min_bars`: the number of trailing candles it needs. Asked
for a value it cannot support, a factor returns `None` — never a plausible-looking
wrong number. A factor needing 252 bars on a 90-day series is `None` for every
bar, gets `coverage == 0.0`, and is reported as such.

Cost tiers
----------
Most factors are O(window) arithmetic. A handful (GARCH, HMM) fit a model per bar
and are hundreds of times slower. Those are tagged `cost="slow"` and excluded from
the default panel; pass `include_slow=True` (CLI: `--all-factors`) to opt in. This
keeps `factors BTC` a few seconds rather than a few minutes.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass

from alpha_engine.cache.models import Candle, PriceSeries
from alpha_engine.quant.features import (
    _mean,
    _pstd,
    _svar,
    ema_series,
    hurst_exponent,
    linreg,
    max_drawdown,
    shannon_entropy,
)

_ANNUAL = math.sqrt(252.0)


# ---------------------------------------------------------------------------
# Bars: the column-oriented view a factor reads
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Bars:
    """Column arrays for a whole series, built once per panel.

    Factors read slices of these lists rather than `Candle` objects. The reason
    is purely cost: building a pydantic model per bar per factor dominated
    everything else, and a panel is 500 factors x hundreds of bars. Slicing a
    plain list of floats is a C-level memcpy.

    `volume` is None when *any* bar lacks volume — a partially-populated volume
    column would silently make volume factors wrong rather than absent.
    """

    open: list[float]
    high: list[float]
    low: list[float]
    close: list[float]
    volume: list[float] | None

    def __len__(self) -> int:
        return len(self.close)

    @staticmethod
    def from_candles(candles: Sequence[Candle]) -> Bars:
        vols = [c.volume for c in candles]
        return Bars(
            open=[c.open for c in candles],
            high=[c.high for c in candles],
            low=[c.low for c in candles],
            close=[c.close for c in candles],
            volume=[float(v) for v in vols] if all(v is not None for v in vols) else None,
        )


FactorFn = Callable[[Bars, int], float | None]


@dataclass(frozen=True, slots=True)
class FactorSpec:
    """One factor. `fn(bars, t)` returns the value at bar `t` or None."""

    name: str
    family: str
    min_bars: int
    fn: FactorFn
    cost: str = "fast"  # "fast" | "slow" (slow = fits a model per bar)


# ---------------------------------------------------------------------------
# Slicing helpers. Every one of these refuses to read past `t`.
# ---------------------------------------------------------------------------


def _win(xs: list[float], t: int, n: int) -> list[float] | None:
    """The `n` values ending at index `t` inclusive, or None if unavailable."""
    start = t - n + 1
    if start < 0 or t >= len(xs):
        return None
    return xs[start : t + 1]


def _rets(closes: list[float]) -> list[float] | None:
    """Log returns of a close slice. None if any price is non-positive (a log
    of zero is undefined, not zero)."""
    out: list[float] = []
    for a, b in zip(closes, closes[1:]):
        if a <= 0 or b <= 0:
            return None
        out.append(math.log(b / a))
    return out


def _safe_div(a: float, b: float) -> float | None:
    return a / b if b != 0 else None


# ---------------------------------------------------------------------------
# Array-form volatility estimators.
#
# features.py has candle-form versions of these; the formulas are identical but
# the input shape is not, and rewriting features.py to be column-oriented would
# mean rewriting working, tested code for no user-visible gain.
# ---------------------------------------------------------------------------


def _parkinson(high: list[float], low: list[float]) -> float | None:
    terms = []
    for h, lo in zip(high, low):
        if lo <= 0 or h < lo:
            return None
        terms.append(math.log(h / lo) ** 2)
    if not terms or sum(terms) <= 0:
        return None
    return math.sqrt(_mean(terms) / (4.0 * math.log(2.0))) * _ANNUAL


def _garman_klass(o: list[float], h: list[float], lo: list[float], c: list[float]) -> float | None:
    terms = []
    for oo, hh, ll, cc in zip(o, h, lo, c):
        if ll <= 0 or oo <= 0 or hh < ll:
            return None
        terms.append(
            0.5 * math.log(hh / ll) ** 2 - (2.0 * math.log(2.0) - 1.0) * math.log(cc / oo) ** 2
        )
    if not terms:
        return None
    m = _mean(terms)
    return math.sqrt(m) * _ANNUAL if m > 0 else None


def _yang_zhang(o: list[float], h: list[float], lo: list[float], c: list[float]) -> float | None:
    n = len(c) - 1
    if n < 2:
        return None
    overnight, openclose, rs = [], [], []
    for i in range(1, len(c)):
        if min(c[i - 1], o[i], c[i], h[i], lo[i]) <= 0:
            return None
        overnight.append(math.log(o[i] / c[i - 1]))
        openclose.append(math.log(c[i] / o[i]))
        rs.append(
            math.log(h[i] / c[i]) * math.log(h[i] / o[i])
            + math.log(lo[i] / c[i]) * math.log(lo[i] / o[i])
        )
    k = 0.34 / (1.34 + (n + 1) / (n - 1))
    var = _svar(overnight) + k * _svar(openclose) + (1.0 - k) * _mean(rs)
    return math.sqrt(var) * _ANNUAL if var >= 0 else None


def _true_ranges(h: list[float], lo: list[float], c: list[float]) -> list[float]:
    """True range for bars 1..n-1 (bar 0 has no previous close)."""
    return [
        max(h[i] - lo[i], abs(h[i] - c[i - 1]), abs(lo[i] - c[i - 1])) for i in range(1, len(c))
    ]


def _corr(xs: list[float], ys: list[float]) -> float | None:
    if len(xs) != len(ys) or len(xs) < 3:
        return None
    sx, sy = _pstd(xs), _pstd(ys)
    if sx == 0 or sy == 0:
        return None
    mx, my = _mean(xs), _mean(ys)
    cov = _mean([(x - mx) * (y - my) for x, y in zip(xs, ys)])
    return max(-1.0, min(1.0, cov / (sx * sy)))


def _wma(xs: list[float]) -> float:
    """Linearly weighted moving average: the most recent bar weighs the most."""
    n = len(xs)
    denom = n * (n + 1) / 2.0
    return sum((i + 1) * x for i, x in enumerate(xs)) / denom


def _pct_rank(x: float, xs: list[float]) -> float:
    return sum(1 for v in xs if v <= x) / len(xs)


# ---------------------------------------------------------------------------
# The N grid. One place to widen or narrow the whole library.
# ---------------------------------------------------------------------------

N_GRID: tuple[int, ...] = (1, 2, 3, 5, 10, 15, 20, 30, 40, 60, 90, 120, 180, 252)
VOL_GRID: tuple[int, ...] = (5, 10, 15, 20, 30, 40, 60, 90, 120, 180, 252)
MA_GRID: tuple[int, ...] = (5, 10, 20, 50, 100, 200)
MID_GRID: tuple[int, ...] = (5, 10, 20, 40, 60, 120)
LONG_GRID: tuple[int, ...] = (60, 120, 252)

FACTOR_REGISTRY: dict[str, FactorSpec] = {}


def register(spec: FactorSpec) -> None:
    """Add a factor. Duplicate names are a bug, not a silent overwrite — a
    shadowed factor would vanish from the rankings with no error anywhere."""
    if spec.name in FACTOR_REGISTRY:
        raise ValueError(f"duplicate factor name: {spec.name}")
    FACTOR_REGISTRY[spec.name] = spec


def _add(name: str, family: str, min_bars: int, fn: FactorFn, cost: str = "fast") -> None:
    register(FactorSpec(name=name, family=family, min_bars=min_bars, fn=fn, cost=cost))


# ---------------------------------------------------------------------------
# Family 1 — momentum / reversal
# ---------------------------------------------------------------------------


def _mom(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None or w[0] <= 0:
            return None
        return w[-1] / w[0] - 1.0

    return fn


def _mom_volnorm(n: int) -> FactorFn:
    """Momentum divided by the volatility of the same window. Puts a 2% move in
    a calm tape and a 2% move in a violent one on the same scale."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None or w[0] <= 0:
            return None
        r = _rets(w)
        if r is None or len(r) < 2:
            return None
        sd = _pstd(r)
        return _safe_div(w[-1] / w[0] - 1.0, sd)

    return fn


def _mom_skip1(n: int) -> FactorFn:
    """Return from t-n to t-1, skipping the most recent bar. The classic
    academic momentum construction: the newest bar is dominated by short-term
    reversal, so leaving it out isolates the slower trend."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 2)
        if w is None or w[0] <= 0:
            return None
        return w[-2] / w[0] - 1.0

    return fn


def _mom_accel(n: int) -> FactorFn:
    """Recent momentum minus the momentum of the window twice as long. Positive
    = the move is speeding up rather than just continuing."""

    def fn(b: Bars, t: int) -> float | None:
        a, c = _mom(n)(b, t), _mom(2 * n)(b, t)
        if a is None or c is None:
            return None
        return a - c

    return fn


def _mom_rank(n: int, hist: int) -> FactorFn:
    """Percentile rank of the current n-bar return within its own last `hist`
    bars of history. Scale-free, so a 5% move means something different in a
    quiet asset than a wild one — which raw momentum cannot express."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, hist + n + 1)
        if w is None:
            return None
        rolls = [w[i] / w[i - n] - 1.0 for i in range(n, len(w)) if w[i - n] > 0]
        if len(rolls) < 10:
            return None
        return _pct_rank(rolls[-1], rolls)

    return fn


for _n in N_GRID:
    _add(f"mom_{_n}", "momentum", _n + 1, _mom(_n))
    # vol-normalizing needs at least two returns to have a deviation at all,
    # so the 1-bar variant is skipped rather than registered as a permanent None
    if _n >= 2:
        _add(f"mom_volnorm_{_n}", "momentum", _n + 1, _mom_volnorm(_n))
for _n in N_GRID[2:]:  # skip-a-bar is meaningless below ~3 bars
    _add(f"mom_skip1_{_n}", "momentum", _n + 2, _mom_skip1(_n))
for _n in (5, 10, 20, 60, 120):
    _add(f"mom_accel_{_n}", "momentum", 2 * _n + 1, _mom_accel(_n))
    _add(f"mom_rank_{_n}", "momentum", 252 + _n + 1, _mom_rank(_n, 252))


# ---------------------------------------------------------------------------
# Family 2 — moving-average structure
# ---------------------------------------------------------------------------


def _ma_value(kind: str, w: list[float]) -> float | None:
    if kind == "sma":
        return _mean(w)
    if kind == "wma":
        return _wma(w)
    e = ema_series(w, len(w))
    return e[-1] if e else None


def _dist_ma(kind: str, n: int) -> FactorFn:
    """Percent distance of price from its moving average — the stretch."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        ma = _ma_value(kind, w)
        if ma is None or ma <= 0:
            return None
        return w[-1] / ma - 1.0

    return fn


def _ma_slope(kind: str, n: int) -> FactorFn:
    """Percent change of the moving average over the last ~n/4 bars. Direction
    of the average rather than distance from it."""
    lag = max(1, n // 4)

    def fn(b: Bars, t: int) -> float | None:
        now = _win(b.close, t, n)
        prev = _win(b.close, t - lag, n)
        if now is None or prev is None:
            return None
        a, c = _ma_value(kind, prev), _ma_value(kind, now)
        if a is None or c is None or a <= 0:
            return None
        return c / a - 1.0

    return fn


def _ma_cross(kind: str, fast: int, slow: int) -> FactorFn:
    """Fast MA minus slow MA, normalized by the slow MA. Positive = the classic
    golden-cross posture."""

    def fn(b: Bars, t: int) -> float | None:
        wf, ws = _win(b.close, t, fast), _win(b.close, t, slow)
        if wf is None or ws is None:
            return None
        a, c = _ma_value(kind, wf), _ma_value(kind, ws)
        if a is None or c is None or c <= 0:
            return None
        return a / c - 1.0

    return fn


_MA_KINDS = ("sma", "ema", "wma")
_MA_PAIRS = [(f, s) for f in MA_GRID for s in MA_GRID if f < s]

for _kind in _MA_KINDS:
    for _n in N_GRID[3:]:  # a 1-2 bar "average" is just the price
        _add(f"dist_{_kind}_{_n}", "ma_structure", _n, _dist_ma(_kind, _n))
        _add(f"slope_{_kind}_{_n}", "ma_structure", _n + max(1, _n // 4), _ma_slope(_kind, _n))
    for _f, _s in _MA_PAIRS:
        _add(f"cross_{_kind}_{_f}_{_s}", "ma_structure", _s, _ma_cross(_kind, _f, _s))


# ---------------------------------------------------------------------------
# Family 3 — volatility
# ---------------------------------------------------------------------------


def _realized_vol(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 2:
            return None
        return _pstd(r) * _ANNUAL

    return fn


def _semivol(n: int, downside: bool) -> FactorFn:
    """Volatility of only the down (or only the up) returns. A tape that falls
    violently and rises gently has the same realized vol as the reverse; these
    two do not."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None:
            return None
        side = [x for x in r if (x < 0 if downside else x > 0)]
        if len(side) < 2:
            return None
        return _pstd(side) * _ANNUAL

    return fn


def _range_vol(kind: str, n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        need = n + 1 if kind == "yz" else n
        if t - need + 1 < 0:
            return None
        o = _win(b.open, t, need)
        h = _win(b.high, t, need)
        lo = _win(b.low, t, need)
        c = _win(b.close, t, need)
        if o is None or h is None or lo is None or c is None:
            return None
        if kind == "parkinson":
            return _parkinson(h, lo)
        if kind == "gk":
            return _garman_klass(o, h, lo, c)
        return _yang_zhang(o, h, lo, c)

    return fn


def _atr_pct(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n + 1), _win(b.low, t, n + 1), _win(b.close, t, n + 1)
        if h is None or lo is None or c is None or c[-1] <= 0:
            return None
        trs = _true_ranges(h, lo, c)
        return _mean(trs) / c[-1] if trs else None

    return fn


def _vol_ratio(short: int, long: int) -> FactorFn:
    """Short-horizon vol over long-horizon vol. Above 1 = the tape just woke up."""

    def fn(b: Bars, t: int) -> float | None:
        a = _realized_vol(short)(b, t)
        c = _realized_vol(long)(b, t)
        if a is None or c is None:
            return None
        return _safe_div(a, c)

    return fn


def _vol_of_vol(n: int) -> FactorFn:
    """Dispersion of rolling 10-bar vol. High = the volatility regime itself is
    unstable, which is different from volatility being high."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 11)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 20:
            return None
        rolling = [_pstd(r[i - 10 : i]) * _ANNUAL for i in range(10, len(r) + 1)]
        return _pstd(rolling)

    return fn


def _vol_percentile(n: int) -> FactorFn:
    """Where current 20-bar vol sits inside its own last-n history. Scale-free,
    so it is comparable across assets in a way raw vol is not."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 21)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 21:
            return None
        hist = [_pstd(r[i - 20 : i]) * _ANNUAL for i in range(20, len(r) + 1)]
        return _pct_rank(hist[-1], hist)

    return fn


def _ewma_vol(n: int, lam: float) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 10:
            return None
        var = _mean([x * x for x in r[:10]])
        for x in r[10:]:
            var = lam * var + (1.0 - lam) * x * x
        return math.sqrt(var) * _ANNUAL

    return fn


for _n in VOL_GRID:
    _add(f"rvol_{_n}", "volatility", _n + 1, _realized_vol(_n))
    _add(f"parkinson_{_n}", "volatility", _n, _range_vol("parkinson", _n))
    _add(f"garman_klass_{_n}", "volatility", _n, _range_vol("gk", _n))
    _add(f"yang_zhang_{_n}", "volatility", _n + 1, _range_vol("yz", _n))
    _add(f"atr_pct_{_n}", "volatility", _n + 1, _atr_pct(_n))
for _n in (20, 60, 120):
    _add(f"semivol_down_{_n}", "volatility", _n + 1, _semivol(_n, downside=True))
    _add(f"semivol_up_{_n}", "volatility", _n + 1, _semivol(_n, downside=False))
for _s, _l in ((5, 20), (10, 60), (20, 120), (20, 252), (60, 252)):
    _add(f"vol_ratio_{_s}_{_l}", "volatility", _l + 1, _vol_ratio(_s, _l))
for _n in (20, 60):
    _add(f"vol_of_vol_{_n}", "volatility", _n + 11, _vol_of_vol(_n))
for _n in LONG_GRID:
    _add(f"vol_percentile_{_n}", "volatility", _n + 21, _vol_percentile(_n))
for _lam in (0.94, 0.97):
    _add(
        f"ewma_vol_{str(_lam).replace('.', '')}",
        "volatility",
        61,
        _ewma_vol(60, _lam),
    )


# ---------------------------------------------------------------------------
# Family 4 — volume / participation
# ---------------------------------------------------------------------------


def _needs_volume(fn: Callable[[Bars, int, list[float]], float | None], n: int) -> FactorFn:
    """Wrap a volume factor so a series without volume returns None everywhere
    rather than raising. Forex and some macro sources have no volume at all."""

    def wrapped(b: Bars, t: int) -> float | None:
        if b.volume is None:
            return None
        v = _win(b.volume, t, n)
        if v is None:
            return None
        return fn(b, t, v)

    return wrapped


def _volume_z(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        sd = _pstd(v)
        return _safe_div(v[-1] - _mean(v), sd)

    return _needs_volume(inner, n)


def _rel_volume(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        return _safe_div(v[-1], _mean(v))

    return _needs_volume(inner, n)


def _volume_percentile(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        return _pct_rank(v[-1], v)

    return _needs_volume(inner, n)


def _obv_slope(n: int) -> FactorFn:
    """Slope of on-balance volume, in units of average daily volume per bar, so
    the number is comparable across assets."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        c = _win(b.close, t, n)
        if c is None:
            return None
        obv, acc = [], 0.0
        for i in range(1, len(c)):
            if c[i] > c[i - 1]:
                acc += v[i]
            elif c[i] < c[i - 1]:
                acc -= v[i]
            obv.append(acc)
        fit = linreg(obv)
        vm = _mean(v)
        if fit is None or vm <= 0:
            return None
        return fit[0] / vm

    return _needs_volume(inner, n)


def _price_volume_corr(n: int) -> FactorFn:
    """Correlation of returns with volume. Positive = moves come with
    participation; negative = the tape drifts on thin volume."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        c = _win(b.close, t, n + 1)
        if c is None:
            return None
        r = _rets(c)
        if r is None or len(r) != len(v):
            return None
        return _corr(r, v)

    return _needs_volume(inner, n)


def _amihud(n: int) -> FactorFn:
    """Amihud illiquidity: average |return| per unit of dollar volume. High =
    small trades move the price a lot = illiquid."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        c = _win(b.close, t, n + 1)
        if c is None:
            return None
        r = _rets(c)
        if r is None or len(r) != len(v):
            return None
        terms = [abs(x) / (vv * cc) for x, vv, cc in zip(r, v, c[1:]) if vv > 0 and cc > 0]
        return _mean(terms) * 1e6 if terms else None

    return _needs_volume(inner, n)


def _dollar_volume_trend(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        c = _win(b.close, t, n)
        if c is None:
            return None
        dv = [vv * cc for vv, cc in zip(v, c)]
        fit = linreg(dv)
        m = _mean(dv)
        if fit is None or m <= 0:
            return None
        return fit[0] / m

    return _needs_volume(inner, n)


def _updown_volume_ratio(n: int) -> FactorFn:
    """Volume on up bars over volume on down bars. Above 1 = buyers are the
    ones showing up."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        c = _win(b.close, t, n)
        if c is None:
            return None
        up = sum(v[i] for i in range(1, len(c)) if c[i] > c[i - 1])
        dn = sum(v[i] for i in range(1, len(c)) if c[i] < c[i - 1])
        return _safe_div(up, dn)

    return _needs_volume(inner, n)


def _dist_vwap(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        num = sum((hh + ll + cc) / 3.0 * vv for hh, ll, cc, vv in zip(h, lo, c, v))
        den = sum(v)
        if den <= 0 or num <= 0:
            return None
        return c[-1] / (num / den) - 1.0

    return _needs_volume(inner, n)


def _volume_trend(n: int) -> FactorFn:
    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        fit = linreg(v)
        m = _mean(v)
        if fit is None or m <= 0:
            return None
        return fit[0] / m

    return _needs_volume(inner, n)


for _n in MID_GRID:
    _add(f"volume_z_{_n}", "volume", _n, _volume_z(_n))
    _add(f"obv_slope_{_n}", "volume", _n, _obv_slope(_n))
    _add(f"price_volume_corr_{_n}", "volume", _n + 1, _price_volume_corr(_n))
    _add(f"volume_trend_{_n}", "volume", _n, _volume_trend(_n))
for _n in (5, 10, 20, 60):
    _add(f"rel_volume_{_n}", "volume", _n, _rel_volume(_n))
    _add(f"dist_vwap_{_n}", "volume", _n, _dist_vwap(_n))
for _n in (20, 60, 120):
    _add(f"amihud_{_n}", "volume", _n + 1, _amihud(_n))
    _add(f"dollar_volume_trend_{_n}", "volume", _n, _dollar_volume_trend(_n))
    _add(f"updown_volume_ratio_{_n}", "volume", _n, _updown_volume_ratio(_n))
for _n in LONG_GRID:
    _add(f"volume_percentile_{_n}", "volume", _n, _volume_percentile(_n))
_add("dist_vwap_120", "volume", 120, _dist_vwap(120))


# ---------------------------------------------------------------------------
# Family 5 — distribution / statistical structure
# ---------------------------------------------------------------------------


def _skew(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 3:
            return None
        sd = _pstd(r)
        if sd <= 0:
            return None
        m = _mean(r)
        return _mean([((x - m) / sd) ** 3 for x in r])

    return fn


def _kurtosis(n: int) -> FactorFn:
    """Excess kurtosis: how fat the tails are relative to a normal (which is 0)."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 4:
            return None
        sd = _pstd(r)
        if sd <= 0:
            return None
        m = _mean(r)
        return _mean([((x - m) / sd) ** 4 for x in r]) - 3.0

    return fn


def _autocorr(lag: int, n: int) -> FactorFn:
    """Correlation of returns with themselves `lag` bars ago. Positive =
    trending at that lag; negative = mean-reverting."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + lag + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < n + lag:
            return None
        return _corr(r[:-lag], r[lag:])

    return fn


def _variance_ratio(q: int, n: int) -> FactorFn:
    """Lo-MacKinlay variance ratio: variance of q-bar returns over q x variance
    of 1-bar returns. 1.0 = random walk, >1 = trending, <1 = mean-reverting."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < q * 4:
            return None
        v1 = _svar(r)
        agg = [sum(r[i : i + q]) for i in range(0, len(r) - q + 1)]
        if v1 <= 0 or len(agg) < 2:
            return None
        return _svar(agg) / (q * v1)

    return fn


def _zscore(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        return _safe_div(w[-1] - _mean(w), _pstd(w))

    return fn


def _entropy(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        return shannon_entropy(r) if r else None

    return fn


def _hurst(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        return hurst_exponent(w, max_points=n) if w else None

    return fn


def _max_dd(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        return max_drawdown(w) if w else None

    return fn


def _positive_bar_share(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if not r:
            return None
        return sum(1 for x in r if x > 0) / len(r)

    return fn


def _tail_ratio(n: int) -> FactorFn:
    """95th percentile return over |5th percentile|. Above 1 = the good tail is
    bigger than the bad one."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 20:
            return None
        s = sorted(r)
        hi = s[int(0.95 * (len(s) - 1))]
        lo = s[int(0.05 * (len(s) - 1))]
        return _safe_div(hi, abs(lo))

    return fn


for _n in (10, 20, 60, 120, 252):
    _add(f"skew_{_n}", "distribution", _n + 1, _skew(_n))
    _add(f"kurtosis_{_n}", "distribution", _n + 1, _kurtosis(_n))
    _add(f"zscore_{_n}", "distribution", _n, _zscore(_n))
for _n in (20, 60, 120, 252):
    for _lag in range(1, 11):
        _add(f"autocorr_lag{_lag}_{_n}", "distribution", _n + _lag + 1, _autocorr(_lag, _n))
for _q in (2, 4, 8, 16):
    for _n in (120, 252):
        _add(f"variance_ratio_{_q}_{_n}", "distribution", _n + 1, _variance_ratio(_q, _n))
for _n in (20, 60, 120):
    _add(f"entropy_{_n}", "distribution", _n + 1, _entropy(_n))
    _add(f"positive_bar_share_{_n}", "distribution", _n + 1, _positive_bar_share(_n))
for _n in (64, 128, 252):
    _add(f"hurst_{_n}", "distribution", _n, _hurst(_n))
for _n in LONG_GRID:
    _add(f"max_drawdown_{_n}", "distribution", _n, _max_dd(_n))
    _add(f"tail_ratio_{_n}", "distribution", _n + 1, _tail_ratio(_n))


# ---------------------------------------------------------------------------
# Family 6 — trend quality
# ---------------------------------------------------------------------------


def _lr(field: str, n: int, part: str) -> FactorFn:
    """Least-squares fit over the window. `part` picks slope (normalized to
    percent-per-bar), r2 (how straight the move was), or the slope's t-stat."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        ys = w
        if field == "log":
            if any(x <= 0 for x in w):
                return None
            ys = [math.log(x) for x in w]
        fit = linreg(ys)
        if fit is None:
            return None
        slope, intercept, r2 = fit
        if part == "r2":
            return r2
        if part == "slope":
            if field == "log":
                return slope
            m = _mean(ys)
            return slope / m if m > 0 else None
        # t-stat of the slope: slope / standard error of slope
        nn = len(ys)
        if nn < 4:
            return None
        resid = [y - (intercept + slope * i) for i, y in enumerate(ys)]
        sse = sum(e * e for e in resid)
        mx = _mean([float(i) for i in range(nn)])
        sxx = sum((i - mx) ** 2 for i in range(nn))
        if sse <= 0 or sxx <= 0:
            return None
        se = math.sqrt(sse / (nn - 2) / sxx)
        return _safe_div(slope, se)

    return fn


def _slope_stability(n: int) -> FactorFn:
    """Dispersion of rolling 20-bar slopes. Low = the trend has been steady;
    high = the trend keeps changing its mind."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None or len(w) < 40:
            return None
        slopes = []
        for i in range(20, len(w) + 1):
            fit = linreg(w[i - 20 : i])
            m = _mean(w[i - 20 : i])
            if fit is not None and m > 0:
                slopes.append(fit[0] / m)
        return _pstd(slopes) if len(slopes) >= 3 else None

    return fn


def _efficiency_ratio(n: int) -> FactorFn:
    """Kaufman efficiency: net move over total path travelled. 1.0 = a straight
    line, near 0 = the same distance covered by thrashing."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        net = abs(w[-1] - w[0])
        path = sum(abs(y - x) for x, y in zip(w, w[1:]))
        return _safe_div(net, path)

    return fn


def _adx(n: int) -> FactorFn:
    """Average Directional Index: trend strength regardless of direction."""

    def fn(b: Bars, t: int) -> float | None:
        need = 2 * n + 1
        h, lo, c = _win(b.high, t, need), _win(b.low, t, need), _win(b.close, t, need)
        if h is None or lo is None or c is None:
            return None
        trs, plus_dm, minus_dm = [], [], []
        for i in range(1, len(c)):
            up, down = h[i] - h[i - 1], lo[i - 1] - lo[i]
            plus_dm.append(up if up > down and up > 0 else 0.0)
            minus_dm.append(down if down > up and down > 0 else 0.0)
            trs.append(max(h[i] - lo[i], abs(h[i] - c[i - 1]), abs(lo[i] - c[i - 1])))
        dxs = []
        for i in range(n, len(trs) + 1):
            tr = sum(trs[i - n : i])
            if tr <= 0:
                continue
            pdi = 100.0 * sum(plus_dm[i - n : i]) / tr
            mdi = 100.0 * sum(minus_dm[i - n : i]) / tr
            if pdi + mdi > 0:
                dxs.append(100.0 * abs(pdi - mdi) / (pdi + mdi))
        return _mean(dxs) if len(dxs) >= 2 else None

    return fn


def _trend_persistence(n: int) -> FactorFn:
    """Share of bars whose direction agreed with the window's net direction."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if not r:
            return None
        net = sum(r)
        if net == 0:
            return 0.5
        return sum(1 for x in r if (x > 0) == (net > 0)) / len(r)

    return fn


def _macd_hist(fast: int, slow: int, signal: int) -> FactorFn:
    """MACD histogram normalized by price, so it is comparable across assets."""

    def fn(b: Bars, t: int) -> float | None:
        need = slow + signal + 10
        w = _win(b.close, t, need)
        if w is None:
            return None
        ef, es = ema_series(w, fast), ema_series(w, slow)
        if not ef or not es:
            return None
        macd = [a - c for a, c in zip(ef[-len(es) :], es)]
        sig = ema_series(macd, signal)
        if not sig or w[-1] <= 0:
            return None
        return (macd[-1] - sig[-1]) / w[-1]

    return fn


for _n in (5, 10, 20, 30, 60, 90, 120, 180, 252):
    _add(f"lr_slope_{_n}", "trend_quality", _n, _lr("price", _n, "slope"))
    _add(f"lr_r2_{_n}", "trend_quality", _n, _lr("price", _n, "r2"))
    _add(f"lr_tstat_{_n}", "trend_quality", _n, _lr("price", _n, "tstat"))
for _n in LONG_GRID:
    _add(f"lr_log_slope_{_n}", "trend_quality", _n, _lr("log", _n, "slope"))
    _add(f"lr_log_r2_{_n}", "trend_quality", _n, _lr("log", _n, "r2"))
for _n in (60, 120):
    _add(f"slope_stability_{_n}", "trend_quality", _n, _slope_stability(_n))
for _n in MID_GRID:
    _add(f"efficiency_ratio_{_n}", "trend_quality", _n + 1, _efficiency_ratio(_n))
for _n in (7, 14, 21, 28):
    _add(f"adx_{_n}", "trend_quality", 2 * _n + 1, _adx(_n))
for _n in (10, 20, 60, 120, 252):
    _add(f"trend_persistence_{_n}", "trend_quality", _n + 1, _trend_persistence(_n))
for _f, _s, _sig in ((12, 26, 9), (5, 35, 5)):
    _add(f"macd_hist_{_f}_{_s}_{_sig}", "trend_quality", _s + _sig + 10, _macd_hist(_f, _s, _sig))


# ---------------------------------------------------------------------------
# Family 7 — range / structure
# ---------------------------------------------------------------------------


def _dist_high(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        h, c = _win(b.high, t, n), _win(b.close, t, n)
        if h is None or c is None:
            return None
        hi = max(h)
        return c[-1] / hi - 1.0 if hi > 0 else None

    return fn


def _dist_low(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        lo, c = _win(b.low, t, n), _win(b.close, t, n)
        if lo is None or c is None:
            return None
        low = min(lo)
        return c[-1] / low - 1.0 if low > 0 else None

    return fn


def _range_position(n: int) -> FactorFn:
    """Where price sits inside the n-bar range: 0 = at the low, 1 = at the high."""

    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        hi, low = max(h), min(lo)
        return _safe_div(c[-1] - low, hi - low)

    return fn


def _donchian_width(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None or c[-1] <= 0:
            return None
        return (max(h) - min(lo)) / c[-1]

    return fn


def _consecutive_bars(n: int) -> FactorFn:
    """Signed run length: +3 = three up bars in a row, -2 = two down bars."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if not r:
            return None
        sign = 1 if r[-1] > 0 else -1 if r[-1] < 0 else 0
        if sign == 0:
            return 0.0
        run = 0
        for x in reversed(r):
            if (x > 0) == (sign > 0) and x != 0:
                run += 1
            else:
                break
        return float(run * sign)

    return fn


def _bb_pct_b(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        m, s = _mean(w), _pstd(w)
        if s <= 0:
            return 0.5
        return (w[-1] - (m - 2 * s)) / (4 * s)

    return fn


def _bb_width(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        m = _mean(w)
        return 4 * _pstd(w) / m if m > 0 else None

    return fn


def _keltner_width(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n + 1), _win(b.low, t, n + 1), _win(b.close, t, n + 1)
        if h is None or lo is None or c is None:
            return None
        trs = _true_ranges(h, lo, c)
        e = ema_series(c, len(c))
        if not trs or not e or e[-1] <= 0:
            return None
        return 4.0 * _mean(trs) / e[-1]

    return fn


def _compression(short: int, long: int) -> FactorFn:
    """Positive = recent ranges are tighter than the longer window (a coil)."""

    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, long + 1), _win(b.low, t, long + 1), _win(b.close, t, long + 1)
        if h is None or lo is None or c is None:
            return None
        trs = _true_ranges(h, lo, c)
        if len(trs) < long:
            return None
        recent, baseline = _mean(trs[-short:]), _mean(trs[-long:])
        return 1.0 - recent / baseline if baseline > 0 else None

    return fn


def _range_percentile(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        rngs = [(hh - ll) / cc for hh, ll, cc in zip(h, lo, c) if cc > 0]
        return _pct_rank(rngs[-1], rngs) if rngs else None

    return fn


def _gap_pct(b: Bars, t: int) -> float | None:
    if t < 1 or b.close[t - 1] <= 0:
        return None
    return b.open[t] / b.close[t - 1] - 1.0


def _mean_gap(n: int) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        o, c = _win(b.open, t, n), _win(b.close, t, n)
        if o is None or c is None or t - n < 0:
            return None
        prev_c = b.close[t - n : t]
        gaps = [oo / pc - 1.0 for oo, pc in zip(o, prev_c) if pc > 0]
        return _mean(gaps) if gaps else None

    return fn


def _candle_part(part: str) -> FactorFn:
    """Shape of the most recent bar: body share, wick shares, and close
    location value (where it closed inside its own range)."""

    def fn(b: Bars, t: int) -> float | None:
        o, h, lo, c = b.open[t], b.high[t], b.low[t], b.close[t]
        full = h - lo
        if full <= 0:
            return None
        if part == "body":
            return abs(c - o) / full
        if part == "upper_wick":
            return (h - max(o, c)) / full
        if part == "lower_wick":
            return (min(o, c) - lo) / full
        return ((c - lo) - (h - c)) / full

    return fn


for _n in (5, 10, 20, 40, 60, 120, 252):
    _add(f"dist_high_{_n}", "range_structure", _n, _dist_high(_n))
    _add(f"dist_low_{_n}", "range_structure", _n, _dist_low(_n))
    _add(f"range_position_{_n}", "range_structure", _n, _range_position(_n))
    _add(f"donchian_width_{_n}", "range_structure", _n, _donchian_width(_n))
for _n in (20, 60):
    _add(f"bb_pct_b_{_n}", "range_structure", _n, _bb_pct_b(_n))
    _add(f"bb_width_{_n}", "range_structure", _n, _bb_width(_n))
    _add(f"keltner_width_{_n}", "range_structure", _n + 1, _keltner_width(_n))
    _add(f"consecutive_bars_{_n}", "range_structure", _n + 1, _consecutive_bars(_n))
for _s, _l in ((5, 20), (10, 60)):
    _add(f"compression_{_s}_{_l}", "range_structure", _l + 1, _compression(_s, _l))
for _n in LONG_GRID:
    _add(f"range_percentile_{_n}", "range_structure", _n, _range_percentile(_n))
for _n in (20, 60):
    _add(f"mean_gap_{_n}", "range_structure", _n + 1, _mean_gap(_n))
_add("gap_pct", "range_structure", 2, _gap_pct)
for _part in ("body", "upper_wick", "lower_wick", "clv"):
    _add(f"candle_{_part}", "range_structure", 1, _candle_part(_part))


# ---------------------------------------------------------------------------
# Family 8 — classic oscillators
#
# These are the textbook indicators (RSI, stochastics, CCI, Williams %R, money
# flow). The registry had none of them: `analyzers/rsi.py` computes RSI for the
# signal path, but it was never available as a *rankable* factor, so nobody
# could measure whether RSI predicts anything on a given asset. Now it is.
# ---------------------------------------------------------------------------


def _rsi(n: int) -> FactorFn:
    """Wilder's RSI: average gain over average loss, mapped to 0-100."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        gains = [max(0.0, y - x) for x, y in zip(w, w[1:])]
        losses = [max(0.0, x - y) for x, y in zip(w, w[1:])]
        ag, al = _mean(gains), _mean(losses)
        if ag + al == 0:
            return 50.0
        return 100.0 * ag / (ag + al)

    return fn


def _stochastic(n: int, smooth: int) -> FactorFn:
    """%K (smooth=1) or %D (smooth>1): where the close sits in the n-bar
    high-low range, optionally averaged over the last `smooth` values."""

    def fn(b: Bars, t: int) -> float | None:
        vals = []
        for i in range(t - smooth + 1, t + 1):
            h, lo, c = _win(b.high, i, n), _win(b.low, i, n), _win(b.close, i, n)
            if h is None or lo is None or c is None:
                return None
            hi, low = max(h), min(lo)
            k = _safe_div(c[-1] - low, hi - low)
            if k is None:
                return None
            vals.append(100.0 * k)
        return _mean(vals) if vals else None

    return fn


def _cci(n: int) -> FactorFn:
    """Commodity Channel Index: typical price versus its average, scaled by
    mean absolute deviation."""

    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        tp = [(hh + ll + cc) / 3.0 for hh, ll, cc in zip(h, lo, c)]
        m = _mean(tp)
        mad = _mean([abs(x - m) for x in tp])
        return _safe_div(tp[-1] - m, 0.015 * mad)

    return fn


def _williams_r(n: int) -> FactorFn:
    """Williams %R: the stochastic read inverted, on a -100..0 scale."""

    def fn(b: Bars, t: int) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        hi, low = max(h), min(lo)
        r = _safe_div(hi - c[-1], hi - low)
        return -100.0 * r if r is not None else None

    return fn


def _money_flow_index(n: int) -> FactorFn:
    """RSI computed on money flow (typical price x volume) rather than price."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        tp = [(hh + ll + cc) / 3.0 for hh, ll, cc in zip(h, lo, c)]
        pos = sum(tp[i] * v[i] for i in range(1, len(tp)) if tp[i] > tp[i - 1])
        neg = sum(tp[i] * v[i] for i in range(1, len(tp)) if tp[i] < tp[i - 1])
        if pos + neg == 0:
            return 50.0
        return 100.0 * pos / (pos + neg)

    return _needs_volume(inner, n)


def _chaikin_money_flow(n: int) -> FactorFn:
    """Volume weighted by where each bar closed inside its own range. Positive
    = volume is arriving on closes near the highs."""

    def inner(b: Bars, t: int, v: list[float]) -> float | None:
        h, lo, c = _win(b.high, t, n), _win(b.low, t, n), _win(b.close, t, n)
        if h is None or lo is None or c is None:
            return None
        num = 0.0
        for hh, ll, cc, vv in zip(h, lo, c, v):
            rng = hh - ll
            if rng > 0:
                num += ((cc - ll) - (hh - cc)) / rng * vv
        return _safe_div(num, sum(v))

    return _needs_volume(inner, n)


for _n in (7, 14, 21, 28):
    _add(f"rsi_{_n}", "oscillator", _n + 1, _rsi(_n))
for _n in (14, 28):
    _add(f"stoch_k_{_n}", "oscillator", _n, _stochastic(_n, 1))
    _add(f"stoch_d_{_n}", "oscillator", _n + 2, _stochastic(_n, 3))
    _add(f"williams_r_{_n}", "oscillator", _n, _williams_r(_n))
    _add(f"money_flow_index_{_n}", "oscillator", _n, _money_flow_index(_n))
for _n in (20, 40):
    _add(f"cci_{_n}", "oscillator", _n, _cci(_n))
for _n in (20, 60):
    _add(f"chaikin_money_flow_{_n}", "oscillator", _n, _chaikin_money_flow(_n))


# ---------------------------------------------------------------------------
# Family 9 — risk-adjusted return
#
# Return per unit of pain. These are the shapes a track record is judged by,
# and they behave differently from raw momentum: an asset can have strong
# momentum and a terrible Sharpe if it got there through violent swings.
# ---------------------------------------------------------------------------


def _sharpe(n: int) -> FactorFn:
    """Mean return over its standard deviation, annualized. No risk-free rate
    subtracted: this is a cross-sectional ranking factor, not a fund report,
    and a constant offset does not change a rank."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 3:
            return None
        return _safe_div(_mean(r) * 252.0, _pstd(r) * _ANNUAL)

    return fn


def _sortino(n: int) -> FactorFn:
    """Sharpe but penalizing only downside deviation. Upside volatility is not
    a problem anyone actually has."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None or len(r) < 3:
            return None
        down = [x for x in r if x < 0]
        if len(down) < 2:
            return None
        return _safe_div(_mean(r) * 252.0, _pstd(down) * _ANNUAL)

    return fn


def _calmar(n: int) -> FactorFn:
    """Return over worst drawdown across the window."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None or w[0] <= 0:
            return None
        dd = max_drawdown(w)
        if dd is None or dd >= 0:
            return None
        return (w[-1] / w[0] - 1.0) / abs(dd)

    return fn


def _ulcer_index(n: int) -> FactorFn:
    """Root-mean-square drawdown: unlike max drawdown, it cares how *long* the
    asset stayed underwater, not just how deep it went."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        peak = w[0]
        sq = []
        for x in w:
            peak = max(peak, x)
            if peak > 0:
                sq.append((100.0 * (x / peak - 1.0)) ** 2)
        return math.sqrt(_mean(sq)) if sq else None

    return fn


def _drawdown_now(n: int) -> FactorFn:
    """Current distance below the running peak — where the asset is *now*,
    as opposed to the worst it ever got."""

    def fn(b: Bars, t: int) -> float | None:
        w = _win(b.close, t, n)
        if w is None:
            return None
        peak = max(w)
        return w[-1] / peak - 1.0 if peak > 0 else None

    return fn


for _n in (20, 60, 120, 252):
    _add(f"sharpe_{_n}", "risk_adjusted", _n + 1, _sharpe(_n))
    _add(f"ulcer_index_{_n}", "risk_adjusted", _n, _ulcer_index(_n))
    _add(f"drawdown_now_{_n}", "risk_adjusted", _n, _drawdown_now(_n))
for _n in (60, 120, 252):
    _add(f"sortino_{_n}", "risk_adjusted", _n + 1, _sortino(_n))
for _n in (120, 252):
    _add(f"calmar_{_n}", "risk_adjusted", _n, _calmar(_n))


# ---------------------------------------------------------------------------
# Family 10 — derived-model factors
#
# Kalman is a single O(n) pass and stays "fast". GARCH and HMM each run an
# iterative fit; at one fit per bar per factor they are ~100x the cost of
# everything else in this file combined, so they are tagged "slow" and left out
# of the default panel. This is a real ceiling, not a guess: measure before
# assuming it changed.
# ---------------------------------------------------------------------------


def _kalman(n: int, part: str) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        from alpha_engine.quant.models import kalman_fair_value

        w = _win(b.close, t, n)
        if w is None:
            return None
        k = kalman_fair_value(w)
        if k is None:
            return None
        return k.distance if part == "distance" else k.slope

    return fn


def _garch(n: int, part: str) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        from alpha_engine.quant.models import fit_garch

        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None:
            return None
        g = fit_garch(r)
        if g is None:
            return None
        if part == "forecast":
            return g.forecast_vol_annual
        rv = _pstd(r) * _ANNUAL
        return _safe_div(g.forecast_vol_annual, rv)

    return fn


def _hmm(n: int, part: str) -> FactorFn:
    def fn(b: Bars, t: int) -> float | None:
        from alpha_engine.quant.models import fit_hmm

        w = _win(b.close, t, n + 1)
        if w is None:
            return None
        r = _rets(w)
        if r is None:
            return None
        h = fit_hmm(r)
        if h is None:
            return None
        # regime_spread: how far apart the two states' means are. A wide spread
        # means the regime split is real; a narrow one means the fit found two
        # states that are barely different, and bull_prob is not worth much.
        return h.bull_prob if part == "bull_prob" else h.bull_mean - h.bear_mean

    return fn


def _roc(base: FactorFn, lag: int) -> FactorFn:
    """Rate of change of another factor: its value now minus `lag` bars ago."""

    def fn(b: Bars, t: int) -> float | None:
        if t - lag < 0:
            return None
        a, c = base(b, t), base(b, t - lag)
        if a is None or c is None:
            return None
        return a - c

    return fn


for _n in (120, 252):
    _add(f"kalman_distance_{_n}", "model", _n, _kalman(_n, "distance"))
    _add(f"kalman_slope_{_n}", "model", _n, _kalman(_n, "slope"))
    _add(f"kalman_distance_roc5_{_n}", "model", _n + 5, _roc(_kalman(_n, "distance"), 5))
    _add(f"garch_forecast_{_n}", "model", _n + 1, _garch(_n, "forecast"), cost="slow")
    _add(f"garch_rv_ratio_{_n}", "model", _n + 1, _garch(_n, "ratio"), cost="slow")
    _add(f"hmm_bull_prob_{_n}", "model", _n + 1, _hmm(_n, "bull_prob"), cost="slow")
    _add(f"hmm_regime_spread_{_n}", "model", _n + 1, _hmm(_n, "spread"), cost="slow")
_add("hmm_bull_prob_roc5_252", "model", 258, _roc(_hmm(252, "bull_prob"), 5), cost="slow")


# ---------------------------------------------------------------------------
# Panel construction
# ---------------------------------------------------------------------------


def factor_names(
    families: Sequence[str] | None = None,
    include_slow: bool = False,
) -> list[str]:
    """Registry names, optionally filtered by family and cost tier."""
    return [
        name
        for name, spec in FACTOR_REGISTRY.items()
        if (families is None or spec.family in families) and (include_slow or spec.cost == "fast")
    ]


def compute_panel(
    series: PriceSeries,
    names: Sequence[str] | None = None,
    include_slow: bool = False,
) -> dict[str, list[float | None]]:
    """Compute every requested factor at every bar.

    Returns `dict[factor_name, list[value_or_None]]`, each list exactly as long
    as `series.candles` — the shape `rank_factors` expects.

    Bars before a factor's `min_bars` are None rather than a partial-window
    approximation. That is what makes the `coverage` column in the ranking
    output mean something.
    """
    bars = Bars.from_candles(series.candles)
    n = len(bars)
    selected = list(names) if names is not None else factor_names(include_slow=include_slow)

    panel: dict[str, list[float | None]] = {}
    for name in selected:
        spec = FACTOR_REGISTRY[name]
        col: list[float | None] = [None] * n
        for t in range(spec.min_bars - 1, n):
            try:
                col[t] = spec.fn(bars, t)
            except (ValueError, ZeroDivisionError, OverflowError):
                # A numeric edge case is missing data, not a crashed panel. The
                # factor is None at this bar and coverage records the loss.
                col[t] = None
        panel[name] = col
    return panel


def factor_families() -> dict[str, list[str]]:
    """Factor names grouped by family, for legible reporting."""
    out: dict[str, list[str]] = {}
    for name, spec in FACTOR_REGISTRY.items():
        out.setdefault(spec.family, []).append(name)
    return out


# ---------------------------------------------------------------------------
# Reporting helpers: low-signal flagging and correlation clustering
# ---------------------------------------------------------------------------

LOW_SIGNAL_IC = 0.02


def flag_low_signal(scores: Sequence[object]) -> dict[str, bool]:
    """Mark each family whose factors are all below `LOW_SIGNAL_IC`.

    Roadmap rule: a family that measures as noise stays in the library for
    completeness but is labelled, rather than quietly presented as useful.
    Takes `FactorScore`-like objects (duck-typed on `.name` and `.rank_ic`) so
    this module does not depend on the ranking module.
    """
    best: dict[str, float] = {}
    for s in scores:
        name = getattr(s, "name", None)
        ic = getattr(s, "rank_ic", None)
        spec = FACTOR_REGISTRY.get(name) if isinstance(name, str) else None
        if spec is None or ic is None:
            continue
        best[spec.family] = max(best.get(spec.family, 0.0), abs(float(ic)))
    return {fam: v < LOW_SIGNAL_IC for fam, v in best.items()}


def factor_clusters(
    panel: dict[str, list[float | None]],
    threshold: float = 0.9,
    max_factors: int = 200,
) -> list[list[str]]:
    """Group factors whose values move together, so the ranking output can be
    read as "N independent ideas" rather than "500 rows".

    Greedy single-pass clustering: walk factors in registry order, put each one
    into the first cluster whose representative it correlates with at or above
    `threshold`, else start a new cluster. Greedy is not the optimal clustering,
    but it is deterministic, O(factors x clusters), and answers the only
    question being asked — has this family saturated?

    `max_factors` bounds the cost; correlating 500 columns pairwise is the one
    genuinely quadratic thing here.
    """
    clusters: list[list[str]] = []
    reps: list[list[float | None]] = []

    for name in list(panel)[:max_factors]:
        col = panel[name]
        placed = False
        for i, rep in enumerate(reps):
            pairs = [(a, c) for a, c in zip(col, rep) if a is not None and c is not None]
            if len(pairs) < 10:
                continue
            c = _corr([a for a, _ in pairs], [b for _, b in pairs])
            if c is not None and abs(c) >= threshold:
                clusters[i].append(name)
                placed = True
                break
        if not placed:
            clusters.append([name])
            reps.append(col)

    return clusters
